"""update timestamp mixin

Revision ID: 0d4a1c637680
Revises: 85158a4e4040
Create Date: 2021-02-09 22:38:02.645968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0d4a1c637680"
down_revision = "85158a4e4040"
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### end Alembic commands ###
