"""add table

Revision ID: 12024d03ad89
Revises: c57e9609a97b
Create Date: 2021-02-09 22:40:28.566942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "12024d03ad89"
down_revision = "c57e9609a97b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
