"""adding text to currency table

Revision ID: 13c039f3bd26
Revises: 6e55c8774914
Create Date: 2021-02-11 17:40:16.233975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "13c039f3bd26"
down_revision = "6e55c8774914"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("currency", sa.Column("text", sa.String(length=128), nullable=False))
    op.create_unique_constraint(None, "currency", ["text"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "currency", type_="unique")
    op.drop_column("currency", "text")
    # ### end Alembic commands ###
