"""adding crossref temp

Revision ID: 1475ffd3b4c7
Revises: f73bd5ead0e0
Create Date: 2021-04-06 18:10:54.184491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1475ffd3b4c7"
down_revision = "f73bd5ead0e0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crossref_temp",
        sa.Column("issn", sa.String(length=9), nullable=False),
        sa.PrimaryKeyConstraint("issn"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("crossref_temp")
    # ### end Alembic commands ###
