"""rename synonyms fields

Revision ID: 14b1cab42fad
Revises: 75ff6e385482
Create Date: 2021-03-20 11:41:20.220833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "14b1cab42fad"
down_revision = "75ff6e385482"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "journals",
        sa.Column(
            "journal_synonyms", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.drop_column("journals", "synonyms")
    op.add_column(
        "publishers",
        sa.Column(
            "publisher_synonyms", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.drop_column("publishers", "synonyms")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "publishers",
        sa.Column(
            "synonyms",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("publishers", "publisher_synonyms")
    op.add_column(
        "journals",
        sa.Column(
            "synonyms",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("journals", "journal_synonyms")
    # ### end Alembic commands ###
