"""add issn org table

Revision ID: 19f5bb7e9100
Revises: 54a282bc5ef1
Create Date: 2021-01-22 12:35:22.170801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "19f5bb7e9100"
down_revision = "54a282bc5ef1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "raw_issn_org_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("issn_l", sa.String(length=9), nullable=False),
        sa.Column("issns", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("issn_l"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("raw_issn_org_data")
    # ### end Alembic commands ###
