"""drop foreign key

Revision ID: 21b83c541d09
Revises: 9dab040ad764
Create Date: 2021-02-11 14:22:19.534182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "21b83c541d09"
down_revision = "9dab040ad764"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
