"""drop foreign key

Revision ID: 21b83c541d09
Revises: 9dab040ad764
Create Date: 2021-02-11 14:22:19.534182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "21b83c541d09"
down_revision = "9dab040ad764"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("open_access", "issn_l", existing_type=sa.TEXT(), nullable=False)
    op.create_index(
        op.f("ix_open_access_issn_l"), "open_access", ["issn_l"], unique=False
    )
    op.drop_constraint("open_access_issn_l_fkey", "open_access", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "open_access_issn_l_fkey", "open_access", "journals", ["issn_l"], ["issn_l"]
    )
    op.drop_index(op.f("ix_open_access_issn_l"), table_name="open_access")
    op.alter_column("open_access", "issn_l", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###
