"""drop foreign key

Revision ID: 21b83c541d09
Revises: 9dab040ad764
Create Date: 2021-02-11 14:22:19.534182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "21b83c541d09"
down_revision = "9dab040ad764"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("open_access_staging")
    op.alter_column("open_access", "issn_l", existing_type=sa.TEXT(), nullable=False)
    op.create_index(
        op.f("ix_open_access_issn_l"), "open_access", ["issn_l"], unique=False
    )
    op.drop_constraint("open_access_issn_l_fkey", "open_access", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "open_access_issn_l_fkey", "open_access", "journals", ["issn_l"], ["issn_l"]
    )
    op.drop_index(op.f("ix_open_access_issn_l"), table_name="open_access")
    op.alter_column("open_access", "issn_l", existing_type=sa.TEXT(), nullable=True)
    op.create_table(
        "open_access_staging",
        sa.Column("issn_l", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("title", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("year", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("num_dois", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("num_open", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "open_rate",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("num_green", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "green_rate",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("num_bronze", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "bronze_rate",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("num_hybrid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "hybrid_rate",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("num_gold", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "gold_rate",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("is_in_doaj", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("is_gold_journal", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.UniqueConstraint(
            "issn_l", "year", name="open_access_staging_issn_l_year_key"
        ),
    )
    # ### end Alembic commands ###
