"""add open access table

Revision ID: 23a3b558760d
Revises: 21b83c541d09
Create Date: 2021-02-11 15:23:53.624124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "23a3b558760d"
down_revision = "21b83c541d09"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "open_access",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("issn_l", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("num_dois", sa.Integer(), nullable=True),
        sa.Column("num_open", sa.Integer(), nullable=True),
        sa.Column("open_rate", sa.Float(), nullable=True),
        sa.Column("num_green", sa.Integer(), nullable=True),
        sa.Column("green_rate", sa.Float(), nullable=True),
        sa.Column("num_bronze", sa.Integer(), nullable=True),
        sa.Column("bronze_rate", sa.Float(), nullable=True),
        sa.Column("num_hybrid", sa.Integer(), nullable=True),
        sa.Column("hybrid_rate", sa.Float(), nullable=True),
        sa.Column("num_gold", sa.Integer(), nullable=True),
        sa.Column("gold_rate", sa.Float(), nullable=True),
        sa.Column("is_in_doaj", sa.Boolean(), nullable=True),
        sa.Column("is_gold_journal", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("issn_l", "year"),
    )
    op.create_index(
        op.f("ix_open_access_issn_l"), "open_access", ["issn_l"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_open_access_issn_l"), table_name="open_access")
    op.drop_table("open_access")
    # ### end Alembic commands ###
