"""add doi stats table

Revision ID: 27aa3457e64d
Revises: 931a03ccf7ae
Create Date: 2021-05-09 20:17:17.239051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "27aa3457e64d"
down_revision = "931a03ccf7ae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "doi_stats",
        sa.Column("issn_l", sa.String(length=9), nullable=False),
        sa.Column(
            "dois_by_year", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "sample_dois", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("issn_l"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("doi_stats")
    # ### end Alembic commands ###
