"""modify apc fields

Revision ID: 309c7f5348b4
Revises: 9aa1017cc64b
Create Date: 2021-08-20 10:52:05.163907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "309c7f5348b4"
down_revision = "9aa1017cc64b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "apc_metadata",
        "apc_required",
        nullable=False,
        new_column_name="apc_fully_subsidized",
    )
    op.alter_column(
        "apc_metadata",
        "apc_funded_by",
        new_column_name="apc_subsidized_by",
    )
    op.alter_column("apc_price", "discount_reason", new_column_name="discount_notes")

    op.drop_index("ix_apc_price_new_currency_id", table_name="apc_price")
    op.drop_index("ix_apc_price_new_journal_id", table_name="apc_price")
    op.drop_index("ix_apc_price_new_year", table_name="apc_price")
    op.create_index(
        op.f("ix_apc_price_currency_id"), "apc_price", ["currency_id"], unique=False
    )
    op.create_index(
        op.f("ix_apc_price_journal_id"), "apc_price", ["journal_id"], unique=False
    )
    op.create_index(op.f("ix_apc_price_year"), "apc_price", ["year"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_apc_price_year"), table_name="apc_price")
    op.drop_index(op.f("ix_apc_price_journal_id"), table_name="apc_price")
    op.drop_index(op.f("ix_apc_price_currency_id"), table_name="apc_price")
    op.create_index("ix_apc_price_new_year", "apc_price", ["year"], unique=False)
    op.create_index(
        "ix_apc_price_new_journal_id", "apc_price", ["journal_id"], unique=False
    )
    op.create_index(
        "ix_apc_price_new_currency_id", "apc_price", ["currency_id"], unique=False
    )
    # ### end Alembic commands ###
