"""set issn column as unique

Revision ID: 32d38367dab3
Revises: 672343511dfb
Create Date: 2021-05-25 14:15:56.540971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "32d38367dab3"
down_revision = "672343511dfb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_issn_to_issnl_issn", table_name="issn_to_issnl")
    op.create_index(
        op.f("ix_issn_to_issnl_issn"), "issn_to_issnl", ["issn"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_issn_to_issnl_issn"), table_name="issn_to_issnl")
    op.create_index("ix_issn_to_issnl_issn", "issn_to_issnl", ["issn"], unique=False)
    # ### end Alembic commands ###
