"""change journal column

Revision ID: 52c47a497011
Revises: c0711033e9c0
Create Date: 2021-01-30 15:26:02.736809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "52c47a497011"
down_revision = "c0711033e9c0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "journals", "issn_metadata", ["issn_l"], ["issn_l"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "journals", type_="foreignkey")
    # ### end Alembic commands ###
