"""updating column names

Revision ID: 5e1d2cb02f95
Revises: 8bca1e6fa760
Create Date: 2021-04-15 22:52:12.791044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5e1d2cb02f95"
down_revision = "8bca1e6fa760"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "journal_metadata", sa.Column("is_society_journal", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "journal_metadata",
        sa.Column(
            "society_journal_organizations",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    op.drop_column("journal_metadata", "society_journal_name")
    op.drop_column("journal_metadata", "society_journal")
    op.add_column(
        "journals", sa.Column("is_modified_title", sa.Boolean(), nullable=True)
    )
    op.drop_column("journals", "modified_title")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "journals",
        sa.Column("modified_title", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.drop_column("journals", "is_modified_title")
    op.add_column(
        "journal_metadata",
        sa.Column("society_journal", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "journal_metadata",
        sa.Column(
            "society_journal_name", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("journal_metadata", "society_journal_organizations")
    op.drop_column("journal_metadata", "is_society_journal")
    # ### end Alembic commands ###
