"""add missing journals table

Revision ID: 672343511dfb
Revises: 694364bf685e
Create Date: 2021-05-18 10:52:02.778500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "672343511dfb"
down_revision = "694364bf685e"
branch_labels = None
depends_on = None


def upgrade():
    pass
    # table later refactored
    # ### commands auto generated by Alembic - please adjust! ###

    # op.create_table(
    #     "missing_journals",
    #     sa.Column("issn", sa.String(length=9), nullable=False),
    #     sa.Column("processed", sa.Boolean(), nullable=True),
    #     sa.Column(
    #         "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
    #     ),
    #     sa.PrimaryKeyConstraint("issn"),
    # )
    # ### end Alembic commands ###


def downgrade():
    pass
    # table later refactored
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table("missing_journals")
    # ### end Alembic commands ###
