"""merge open access tables into one

Revision ID: 6e55c8774914
Revises: 744695e84b5d
Create Date: 2021-02-07 09:03:52.928237

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6e55c8774914"
down_revision = "744695e84b5d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
