"""add retraction watch table

Revision ID: 738c030c93d4
Revises: ce6ad4d5b1fa
Create Date: 2021-02-24 14:44:19.900391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "738c030c93d4"
down_revision = "ce6ad4d5b1fa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "retraction_watch",
        sa.Column("record_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("journal", sa.String(length=500), nullable=False),
        sa.Column("publisher", sa.String(length=500), nullable=False),
        sa.Column("retraction_date", sa.DateTime(), nullable=False),
        sa.Column("retraction_doi", sa.String(length=100), nullable=False),
        sa.Column("paper_doi", sa.String(length=100), nullable=False),
        sa.Column("issn", sa.String(length=9), nullable=True),
        sa.PrimaryKeyConstraint("record_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("retraction_watch")
    # ### end Alembic commands ###
