"""add previous issnl field

Revision ID: 77c5d9aaf3c8
Revises: 78407d8c375a
Create Date: 2021-09-02 09:53:18.173929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "77c5d9aaf3c8"
down_revision = "78407d8c375a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "issn_metadata",
        sa.Column(
            "previous_issn_ls", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "journals",
        sa.Column(
            "other_titles", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.drop_column("journals", "journal_synonyms")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "journals",
        sa.Column(
            "journal_synonyms",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("journals", "other_titles")
    op.drop_column("issn_metadata", "previous_issn_ls")
    # ### end Alembic commands ###
