"""rename old subscription table

Revision ID: 78407d8c375a
Revises: d472e8cc6100
Create Date: 2021-08-28 15:48:30.133011

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "78407d8c375a"
down_revision = "d472e8cc6100"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('journal_subscription_price_old')
    # op.drop_table('subscription_price_old')
    op.drop_index(
        "ix_subscription_price_country_id", table_name="subscription_price_old"
    )
    op.drop_index(
        "ix_subscription_price_currency_id", table_name="subscription_price_old"
    )
    op.drop_index(
        "ix_subscription_price_region_id", table_name="subscription_price_old"
    )
    op.drop_index("ix_subscription_price_year", table_name="subscription_price_old")
    op.drop_index(
        "ix_subscription_price_new_country_id", table_name="subscription_price"
    )
    op.drop_index(
        "ix_subscription_price_new_currency_id", table_name="subscription_price"
    )
    op.drop_index(
        "ix_subscription_price_new_journal_id", table_name="subscription_price"
    )
    op.drop_index(
        "ix_subscription_price_new_region_id", table_name="subscription_price"
    )
    op.drop_index("ix_subscription_price_new_year", table_name="subscription_price")
    op.create_index(
        op.f("ix_subscription_price_country_id"),
        "subscription_price",
        ["country_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_price_currency_id"),
        "subscription_price",
        ["currency_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_price_journal_id"),
        "subscription_price",
        ["journal_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_price_region_id"),
        "subscription_price",
        ["region_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_price_year"), "subscription_price", ["year"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscription_price_year"), table_name="subscription_price")
    op.drop_index(
        op.f("ix_subscription_price_region_id"), table_name="subscription_price"
    )
    op.drop_index(
        op.f("ix_subscription_price_journal_id"), table_name="subscription_price"
    )
    op.drop_index(
        op.f("ix_subscription_price_currency_id"), table_name="subscription_price"
    )
    op.drop_index(
        op.f("ix_subscription_price_country_id"), table_name="subscription_price"
    )
    op.create_index(
        "ix_subscription_price_new_year", "subscription_price", ["year"], unique=False
    )
    op.create_index(
        "ix_subscription_price_new_region_id",
        "subscription_price",
        ["region_id"],
        unique=False,
    )
    op.create_index(
        "ix_subscription_price_new_journal_id",
        "subscription_price",
        ["journal_id"],
        unique=False,
    )
    op.create_index(
        "ix_subscription_price_new_currency_id",
        "subscription_price",
        ["currency_id"],
        unique=False,
    )
    op.create_index(
        "ix_subscription_price_new_country_id",
        "subscription_price",
        ["country_id"],
        unique=False,
    )
    op.create_table(
        "subscription_price_old",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('subscription_price_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "price",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("currency_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("country_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("region_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("fte_from", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("fte_to", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("year", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["country_id"], ["countries.id"], name="subscription_price_country_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["currency_id"], ["currency.id"], name="subscription_price_currency_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["region_id"], ["regions.id"], name="subscription_price_region_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="subscription_price_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        "ix_subscription_price_year", "subscription_price_old", ["year"], unique=False
    )
    op.create_index(
        "ix_subscription_price_region_id",
        "subscription_price_old",
        ["region_id"],
        unique=False,
    )
    op.create_index(
        "ix_subscription_price_currency_id",
        "subscription_price_old",
        ["currency_id"],
        unique=False,
    )
    op.create_index(
        "ix_subscription_price_country_id",
        "subscription_price_old",
        ["country_id"],
        unique=False,
    )
    op.create_table(
        "journal_subscription_price_old",
        sa.Column("journal_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "subscription_price_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["journal_id"],
            ["journals.id"],
            name="journal_subscription_price_journal_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_price_id"],
            ["subscription_price_old.id"],
            name="journal_subscription_price_subscription_price_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "journal_id",
            "subscription_price_id",
            name="journal_subscription_price_pkey",
        ),
    )
    # ### end Alembic commands ###
