"""remove journal metadata table

Revision ID: 8136d2440010
Revises: f73bd5ead0e0
Create Date: 2021-04-05 18:52:22.650974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8136d2440010"
down_revision = "f73bd5ead0e0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("journal_metadata")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "journal_metadata",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("journal_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("society_journal", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "society_journal_name", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["journal_id"], ["journals.id"], name="journal_metadata_journal_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="journal_metadata_pkey"),
    )
    # ### end Alembic commands ###
