"""add unique constraint

Revision ID: 85158a4e4040
Revises: fba28ebedc0b
Create Date: 2021-02-09 22:33:56.153383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "85158a4e4040"
down_revision = "fba28ebedc0b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "open_access", ["issn_l", "year"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "open_access", type_="unique")
    # ### end Alembic commands ###
