"""add unique constraint

Revision ID: 85158a4e4040
Revises: fba28ebedc0b
Create Date: 2021-02-09 22:33:56.153383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "85158a4e4040"
down_revision = "fba28ebedc0b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("open_access_staging_issn_l_idx", table_name="open_access_staging")
    op.drop_table("open_access_staging")
    op.create_unique_constraint(None, "open_access", ["issn_l", "year"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "open_access", type_="unique")
    op.create_table(
        "open_access_staging",
        sa.Column("issn_l", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("title", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("year", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("num_dois", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("num_open", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "open_rate",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("num_green", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "green_rate",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("num_bronze", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "bronze_rate",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("num_hybrid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "hybrid_rate",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("num_gold", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "gold_rate",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("is_in_doaj", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("is_gold_journal", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.create_index(
        "open_access_staging_issn_l_idx",
        "open_access_staging",
        ["issn_l"],
        unique=False,
    )
    # ### end Alembic commands ###
