"""add retraction watch summary table

Revision ID: 89df7caa1e08
Revises: 738c030c93d4
Create Date: 2021-02-28 12:13:29.644467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "89df7caa1e08"
down_revision = "738c030c93d4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "retraction_summary",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("issn", sa.String(length=9), nullable=True),
        sa.Column("journal", sa.Text(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("retractions", sa.Integer(), nullable=False),
        sa.Column("num_dois", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("issn", "year"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("retraction_summary")
    # ### end Alembic commands ###
