"""updating unique property for symbols

Revision ID: 8b8b810d90de
Revises: 13c039f3bd26
Create Date: 2021-02-11 17:42:16.452513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8b8b810d90de"
down_revision = "13c039f3bd26"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("currency_symbol_key", "currency", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("currency_symbol_key", "currency", ["symbol"])
    # ### end Alembic commands ###
