"""adding modified_title field

Revision ID: 8bca1e6fa760
Revises: a5fea169e2d3
Create Date: 2021-04-14 17:03:32.519622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8bca1e6fa760"
down_revision = "a5fea169e2d3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("journals", sa.Column("modified_title", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("journals", "modified_title")
    # ### end Alembic commands ###
