"""drop has_crossref columns, crossref temp table

Revision ID: 931a03ccf7ae
Revises: 2c9135e4c015
Create Date: 2021-05-07 09:24:37.971327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "931a03ccf7ae"
down_revision = "2c9135e4c015"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("crossref_temp")
    op.drop_column("issn_metadata", "has_crossref")
    op.drop_column("issn_to_issnl", "has_crossref")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "issn_to_issnl",
        sa.Column("has_crossref", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "issn_metadata",
        sa.Column("has_crossref", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "crossref_temp",
        sa.Column("issn", sa.VARCHAR(length=9), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("issn", name="crossref_temp_pkey"),
    )
    # ### end Alembic commands ###
