"""refactor apc pricing

Revision ID: 9aa1017cc64b
Revises: cce9d107c21a
Create Date: 2021-08-17 14:23:16.940879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9aa1017cc64b"
down_revision = "cce9d107c21a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apc_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("journal_id", sa.Integer(), nullable=False),
        sa.Column("apc_source", sa.String(length=128), nullable=True),
        sa.Column("apc_required", sa.Boolean(), nullable=False),
        sa.Column("apc_funded_by", sa.String(length=128), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["journal_id"],
            ["journals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_apc_metadata_journal_id"), "apc_metadata", ["journal_id"], unique=False
    )
    op.create_table(
        "apc_price_new",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("journal_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency_id", sa.Integer(), nullable=False),
        sa.Column("country_id", sa.Integer(), nullable=True),
        sa.Column("region_id", sa.Integer(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("apc_waived", sa.Boolean(), nullable=False),
        sa.Column("discounted", sa.Boolean(), nullable=False),
        sa.Column("discount_reason", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["countries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["currency_id"],
            ["currency.id"],
        ),
        sa.ForeignKeyConstraint(
            ["journal_id"],
            ["journals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_apc_price_new_currency_id"),
        "apc_price_new",
        ["currency_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_apc_price_new_journal_id"),
        "apc_price_new",
        ["journal_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_apc_price_new_year"), "apc_price_new", ["year"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_apc_price_new_year"), table_name="apc_price_new")
    op.drop_index(op.f("ix_apc_price_new_journal_id"), table_name="apc_price_new")
    op.drop_index(op.f("ix_apc_price_new_currency_id"), table_name="apc_price_new")
    op.drop_table("apc_price_new")
    op.drop_index(op.f("ix_apc_metadata_journal_id"), table_name="apc_metadata")
    op.drop_table("apc_metadata")
    # ### end Alembic commands ###
