"""change field to foreign key

Revision ID: 9dab040ad764
Revises: 12024d03ad89
Create Date: 2021-02-11 14:16:14.499610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9dab040ad764"
down_revision = "12024d03ad89"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("open_access", "issn_l", existing_type=sa.TEXT(), nullable=True)
    op.drop_index("ix_open_access_issn_l", table_name="open_access")
    op.create_foreign_key(None, "open_access", "journals", ["issn_l"], ["issn_l"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "open_access", type_="foreignkey")
    op.create_index("ix_open_access_issn_l", "open_access", ["issn_l"], unique=False)
    op.alter_column("open_access", "issn_l", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###
