"""change field to foreign key

Revision ID: 9dab040ad764
Revises: 12024d03ad89
Create Date: 2021-02-11 14:16:14.499610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9dab040ad764"
down_revision = "12024d03ad89"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
