"""add open access table

Revision ID: 9ec1e528a446
Revises: 594a0424c091
Create Date: 2021-02-09 17:44:55.960763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9ec1e528a446"
down_revision = "594a0424c091"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "open_access",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("issn_l", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("is_in_doaj", sa.Boolean(), nullable=True),
        sa.Column("is_hybrid_journal", sa.Boolean(), nullable=True),
        sa.Column("is_gold_journal", sa.Boolean(), nullable=True),
        sa.Column("is_diamond_oa", sa.Boolean(), nullable=True),
        sa.Column("num_dois", sa.Integer(), nullable=True),
        sa.Column("num_open", sa.Integer(), nullable=True),
        sa.Column("open_rate", sa.Float(), nullable=True),
        sa.Column("num_green", sa.Integer(), nullable=True),
        sa.Column("green_rate", sa.Float(), nullable=True),
        sa.Column("num_bronze", sa.Integer(), nullable=True),
        sa.Column("bronze_rate", sa.Float(), nullable=True),
        sa.Column("num_hybrid", sa.Integer(), nullable=True),
        sa.Column("hybrid_rate", sa.Float(), nullable=True),
        sa.Column("num_gold", sa.Integer(), nullable=True),
        sa.Column("gold_rate", sa.Float(), nullable=True),
        sa.Column("hash", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_open_access_issn_l"), "open_access", ["issn_l"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_open_access_issn_l"), table_name="open_access")
    op.drop_table("open_access")
    # ### end Alembic commands ###
