"""add open access table

Revision ID: 9ec1e528a446
Revises: 594a0424c091
Create Date: 2021-02-09 17:44:55.960763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9ec1e528a446"
down_revision = "594a0424c091"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
