"""empty message

Revision ID: 9f8c327dd506
Revises: eea902e662a9
Create Date: 2021-07-08 15:02:39.906614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "9f8c327dd506"
down_revision = "eea902e662a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    journalstatus = postgresql.ENUM(
        "discontinued",
        "incorporated",
        "publishing",
        "renamed",
        "unknown",
        name="journalstatus",
    )
    journalstatus.create(op.get_bind())
    op.add_column(
        "journals",
        sa.Column(
            "status",
            sa.Enum(
                "ceased",
                "incorporated",
                "publishing",
                "renamed",
                "unknown",
                name="journalstatus",
            ),
            server_default="unknown",
            nullable=False,
        ),
    )
    op.drop_column("journals", "discount_waiver_exception")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "journals",
        sa.Column(
            "discount_waiver_exception",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("journals", "status")
    op.execute("DROP TYPE journalstatus;")
    # ### end Alembic commands ###
