"""society organization to one col

Revision ID: a5fea169e2d3
Revises: e2abdf81151f
Create Date: 2021-04-14 13:47:36.645976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a5fea169e2d3"
down_revision = "e2abdf81151f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("journal_metadata", "society_journal_url")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "journal_metadata",
        sa.Column(
            "society_journal_url",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
