"""removing id from open access

Revision ID: b934f6742be0
Revises: 14b1cab42fad
Create Date: 2021-03-28 21:26:24.381700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b934f6742be0"
down_revision = "14b1cab42fad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("open_access_issn_l_year_key", "open_access", type_="unique")
    op.create_unique_constraint("oa", "open_access", ["issn_l", "year"])
    op.drop_column("open_access", "id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "open_access", sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False)
    )
    op.drop_constraint("oa", "open_access", type_="unique")
    op.create_unique_constraint(
        "open_access_issn_l_year_key", "open_access", ["issn_l", "year"]
    )
    # ### end Alembic commands ###
