"""adding index to ISSNToISSNL

Revision ID: b9c0f72bc63a
Revises: 1475ffd3b4c7
Create Date: 2021-04-06 19:24:54.583828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b9c0f72bc63a"
down_revision = "1475ffd3b4c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_issn_to_issnl_issn"), "issn_to_issnl", ["issn"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_issn_to_issnl_issn"), table_name="issn_to_issnl")
    # ### end Alembic commands ###
