"""making name for region duplicates okay

Revision ID: c3449ed8577e
Revises: d72ed9fd6d0c
Create Date: 2021-02-13 01:24:44.894766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c3449ed8577e"
down_revision = "d72ed9fd6d0c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("regions_name_key", "regions", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("regions_name_key", "regions", ["name"])
    # ### end Alembic commands ###
