"""add table

Revision ID: c57e9609a97b
Revises: 0d4a1c637680
Create Date: 2021-02-09 22:39:41.484499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c57e9609a97b"
down_revision = "0d4a1c637680"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
