"""add status_as_of column

Revision ID: cce9d107c21a
Revises: 9f8c327dd506
Create Date: 2021-07-08 19:16:15.975527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cce9d107c21a"
down_revision = "9f8c327dd506"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("journals", sa.Column("status_as_of", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("journals", "status_as_of")
    # ### end Alembic commands ###
