"""add sub_data_source and unique constraint

Revision ID: ce6ad4d5b1fa
Revises: cdb8756b9e11
Create Date: 2021-02-23 21:05:27.438519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ce6ad4d5b1fa"
down_revision = "cdb8756b9e11"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "publishers", sa.Column("sub_data_source", sa.String(length=500), nullable=True)
    )
    op.create_unique_constraint("uix_1", "repositories", ["issn_l", "endpoint_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_1", "repositories", type_="unique")
    op.drop_column("publishers", "sub_data_source")
    # ### end Alembic commands ###
