"""new subscription table

Revision ID: d472e8cc6100
Revises: e487c3f2bdd0
Create Date: 2021-08-28 10:34:02.566215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d472e8cc6100"
down_revision = "e487c3f2bdd0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription_price_new",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("journal_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency_id", sa.Integer(), nullable=False),
        sa.Column("country_id", sa.Integer(), nullable=True),
        sa.Column("region_id", sa.Integer(), nullable=True),
        sa.Column("fte_from", sa.Integer(), nullable=True),
        sa.Column("fte_to", sa.Integer(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["countries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["currency_id"],
            ["currency.id"],
        ),
        sa.ForeignKeyConstraint(
            ["journal_id"],
            ["journals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscription_price_new_country_id"),
        "subscription_price_new",
        ["country_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_price_new_currency_id"),
        "subscription_price_new",
        ["currency_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_price_new_journal_id"),
        "subscription_price_new",
        ["journal_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_price_new_region_id"),
        "subscription_price_new",
        ["region_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_price_new_year"),
        "subscription_price_new",
        ["year"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_subscription_price_new_year"), table_name="subscription_price_new"
    )
    op.drop_index(
        op.f("ix_subscription_price_new_region_id"), table_name="subscription_price_new"
    )
    op.drop_index(
        op.f("ix_subscription_price_new_journal_id"),
        table_name="subscription_price_new",
    )
    op.drop_index(
        op.f("ix_subscription_price_new_currency_id"),
        table_name="subscription_price_new",
    )
    op.drop_index(
        op.f("ix_subscription_price_new_country_id"),
        table_name="subscription_price_new",
    )
    op.drop_table("subscription_price_new")
    # ### end Alembic commands ###
