"""added acronym to Currency table

Revision ID: d72ed9fd6d0c
Revises: 8b8b810d90de
Create Date: 2021-02-11 18:22:03.036205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d72ed9fd6d0c"
down_revision = "8b8b810d90de"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("currency", sa.Column("acronym", sa.String(length=3), nullable=False))
    op.create_unique_constraint(None, "currency", ["acronym"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "currency", type_="unique")
    op.drop_column("currency", "acronym")
    # ### end Alembic commands ###
