"""modify repository model

Revision ID: da83b6202bb4
Revises: 25138f02595e
Create Date: 2021-02-15 10:36:45.484844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "da83b6202bb4"
down_revision = "25138f02595e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repositories",
        sa.Column("issn_l", sa.Text(), nullable=False),
        sa.Column("endpoint_id", sa.Text(), nullable=False),
        sa.Column("repository_name", sa.Text(), nullable=True),
        sa.Column("institution_name", sa.Text(), nullable=True),
        sa.Column("home_page", sa.Text(), nullable=True),
        sa.Column("pmh_url", sa.Text(), nullable=True),
        sa.Column("num_articles", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("issn_l", "endpoint_id"),
    )
    op.create_index(
        op.f("ix_repositories_issn_l"), "repositories", ["issn_l"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_repositories_issn_l"), table_name="repositories")
    op.drop_table("repositories")
    # ### end Alembic commands ###
