"""add journals_renamed table

Revision ID: eea902e662a9
Revises: 05635d20ceb7
Create Date: 2021-06-24 11:21:12.138330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eea902e662a9"
down_revision = "05635d20ceb7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "journals_renamed",
        sa.Column("current_issn_l", sa.String(length=9), nullable=False),
        sa.Column("former_issn_l", sa.String(length=9), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["current_issn_l"],
            ["journals.issn_l"],
        ),
        sa.ForeignKeyConstraint(
            ["former_issn_l"],
            ["journals.issn_l"],
        ),
        sa.PrimaryKeyConstraint("current_issn_l", "former_issn_l"),
        sa.UniqueConstraint("former_issn_l"),
    )
    op.create_index(
        op.f("ix_journals_renamed_current_issn_l"),
        "journals_renamed",
        ["current_issn_l"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_journals_renamed_current_issn_l"), table_name="journals_renamed"
    )
    op.drop_table("journals_renamed")
    # ### end Alembic commands ###
