"""removing id from open access

Revision ID: f73bd5ead0e0
Revises: b934f6742be0
Create Date: 2021-03-28 21:28:55.872699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f73bd5ead0e0"
down_revision = "b934f6742be0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("oa", "open_access", type_="unique")
    op.create_unique_constraint("oax_1", "open_access", ["issn_l", "year"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("oax_1", "open_access", type_="unique")
    op.create_unique_constraint("oa", "open_access", ["issn_l", "year"])
    # ### end Alembic commands ###
