"""modify open access table

Revision ID: fba28ebedc0b
Revises: 9ec1e528a446
Create Date: 2021-02-09 17:50:20.046962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fba28ebedc0b"
down_revision = "9ec1e528a446"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
